package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"

	"github.com/subvost/xray-tun/backend/internal/rpc"
	"github.com/subvost/xray-tun/backend/internal/runtime"
	"github.com/subvost/xray-tun/backend/internal/shell"
	"github.com/subvost/xray-tun/backend/internal/store"
)

func main() {
	mode := flag.String("mode", "serve", "operating mode: serve, start, stop, diag")
	configHomeFlag := flag.String("store", "", "path to config directory (default from $XDG_CONFIG_HOME or ~/.config)")
	projectRoot := flag.String("project-root", "", "path to project root")
	flag.Parse()

	configHome := resolveConfigHome(*configHomeFlag)

	pr := *projectRoot
	if pr == "" {
		pr = findProjectRoot()
	}

	switch *mode {
	case "serve":
		runServe(configHome)
	case "start":
		runStart(configHome, pr)
	case "stop":
		runStop(configHome, pr)
	case "diag":
		runDiag(configHome, pr)
	default:
		fmt.Fprintf(os.Stderr, "unknown mode: %s\n", *mode)
		os.Exit(1)
	}
}

func resolveConfigHome(flagVal string) string {
	if flagVal != "" {
		return flagVal
	}
	if v := os.Getenv("XDG_CONFIG_HOME"); v != "" {
		return v
	}
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot determine home directory: %v\n", err)
		os.Exit(1)
	}
	return filepath.Join(home, ".config")
}

func findProjectRoot() string {
	if v := os.Getenv("SUBVOST_PROJECT_ROOT"); v != "" {
		return v
	}
	exe, err := os.Executable()
	if err != nil {
		return "."
	}
	return filepath.Dir(exe)
}

func runServe(configHome string) {
	srv := rpc.NewServer(configHome, findProjectRoot())

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGTERM, syscall.SIGINT)

	go func() {
		<-sigCh
		srv.Shutdown()
	}()

	if err := srv.Serve(); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %v\n", err)
		os.Exit(1)
	}
}

func runStart(configHome, projectRoot string) {
	paths := store.BuildAppPaths(configHome)

	// Ensure store is initialized and an active node exists.
	st, err := store.EnsureStoreInitialized(paths)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load store: %v\n", err)
		os.Exit(1)
	}

	_, activeNode := store.GetActiveNode(st)
	if activeNode == nil {
		fmt.Fprintf(os.Stderr, "no active node selected — activate a node first\n")
		os.Exit(1)
	}

	// The runtime config must already exist (generated by prior activate).
	if _, err := os.Stat(paths.ActiveRuntimeXrayConfigFile); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "runtime config not found at %s — activate a node first\n",
			paths.ActiveRuntimeXrayConfigFile)
		os.Exit(1)
	}

	// Check if another instance is already running.
	prevState := runtime.ReadStateFile(paths.StateFile)
	if pidStr, ok := prevState["pid"]; ok {
		var prevPid int
		fmt.Sscanf(pidStr, "%d", &prevPid)
		if prevPid > 0 && runtime.IsXrayAlive(prevPid) {
			fmt.Fprintf(os.Stderr, "xray is already running (pid %d)\n", prevPid)
			os.Exit(1)
		}
	}

	// Find xray binary.
	xrayBin := runtime.FindXrayBinary(projectRoot)
	if xrayBin == "" {
		fmt.Fprintf(os.Stderr, "xray binary not found\n")
		os.Exit(1)
	}

	// Create TUN device.
	tunName := "tun0"
	if err := runtime.CreateTun(tunName, 1500); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create TUN device: %v\n", err)
		os.Exit(1)
	}

	// Setup policy routing.
	fwmark := 0x737562
	table := 100
	if err := runtime.SetupPolicyRouting(tunName, fwmark, table); err != nil {
		fmt.Fprintf(os.Stderr, "failed to setup policy routing: %v\n", err)
		os.Exit(1)
	}

	// Start xray.
	pid, err := runtime.StartXray(paths.ActiveRuntimeXrayConfigFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to start xray: %v\n", err)
		os.Exit(1)
	}

	// Write state file.
	installID := ""
	if v, ok := prevState["install_id"]; ok {
		installID = v
	}
	state := map[string]string{
		"pid":        fmt.Sprintf("%d", pid),
		"tun":        tunName,
		"install_id": installID,
	}
	if err := runtime.WriteStateFile(paths.StateFile, state); err != nil {
		fmt.Fprintf(os.Stderr, "warning: failed to write state file: %v\n", err)
	}

	fmt.Printf("started xray (pid %d)\n", pid)
}

func runStop(configHome, projectRoot string) {
	_ = projectRoot
	paths := store.BuildAppPaths(configHome)

	state := runtime.ReadStateFile(paths.StateFile)
	if state == nil {
		fmt.Fprintf(os.Stderr, "no state file — xray may not be running\n")
		os.Exit(1)
	}

	pidStr, ok := state["pid"]
	if !ok {
		fmt.Fprintf(os.Stderr, "no pid in state file — xray may not be running\n")
		os.Exit(1)
	}

	var pid int
	fmt.Sscanf(pidStr, "%d", &pid)
	if pid <= 0 {
		fmt.Fprintf(os.Stderr, "invalid pid in state file: %s\n", pidStr)
		os.Exit(1)
	}

	if err := runtime.StopXray(pid); err != nil {
		fmt.Fprintf(os.Stderr, "failed to stop xray: %v\n", err)
		os.Exit(1)
	}

	// Teardown TUN and routing.
	tunName := state["tun"]
	if tunName == "" {
		tunName = "tun0"
	}
	table := 100
	if err := runtime.TeardownTun(tunName, table); err != nil {
		fmt.Fprintf(os.Stderr, "warning: failed to teardown TUN: %v\n", err)
	}

	// Clear state file.
	_ = os.Remove(paths.StateFile)

	fmt.Println("stopped")
}

func runDiag(configHome, projectRoot string) {
	_ = configHome

	captureScript := filepath.Join(projectRoot, "libexec", "capture-xray-tun-state.sh")
	if _, err := os.Stat(captureScript); os.IsNotExist(err) {
		captureScript = filepath.Join(projectRoot, "capture-xray-tun-state.sh")
	}

	output, err := shell.Run("bash", captureScript)
	if err != nil {
		fmt.Fprintf(os.Stderr, "diagnostics failed: %v\n", err)
		if output != "" {
			fmt.Print(output)
		}
		os.Exit(1)
	}

	fmt.Print(output)
}
